# Generated by Django 2.1.5 on 2021-08-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='djangoAide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=1000)),
            ],
        ),
        migrations.CreateModel(
            name='djangoGraduation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.DecimalField(decimal_places=2, max_digits=100)),
                ('date', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='djangoSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academy', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=60)),
                ('tuition', models.DecimalField(decimal_places=2, default=0.0, max_digits=10000)),
            ],
        ),
    ]
